[package]
name = "fuzz-afl"
version = "0.0.0"
edition = "2021"
resolver = "2"

[dependencies]
afl = "0.15"
bilrost = { path = "../.." }
common = { path = "../common" }

[[bin]]
name = "bilrost_afl"
path = "src/main.rs"

[[bin]]
name = "create-testmessage"
path = "src/create_testmessage.rs"
