[package]
name = "fuzz"
version = "0.0.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
    "Kent Ross <k@mad.cash>",
]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tests = { path = "../tests" }

[[bin]]
name = "bilrost_fuzz"
path = "fuzzers/bilrost_fuzz.rs"
